//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLL.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///
        ///&lt;svg
        ///   width=&quot;26.458334mm&quot;
        ///   height=&quot;26.45833mm&quot;
        ///   viewBox=&quot;0 0 26.458334 26.45833&quot;
        ///   version=&quot;1.1&quot;
        ///   id=&quot;svg1&quot;
        ///   xml:space=&quot;preserve&quot;
        ///   inkscape:version=&quot;1.4 (86a8ad7, 2024-10-11)&quot;
        ///   sodipodi:docname=&quot;Component_Background.svg&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:xlink=&quot;http://www. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Blue_Led_On {
            get {
                return ResourceManager.GetString("Blue_Led_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///
        ///&lt;svg
        ///   width=&quot;26.458336mm&quot;
        ///   height=&quot;26.45833mm&quot;
        ///   viewBox=&quot;0 0 26.458336 26.45833&quot;
        ///   version=&quot;1.1&quot;
        ///   id=&quot;svg1&quot;
        ///   xml:space=&quot;preserve&quot;
        ///   inkscape:version=&quot;1.4 (86a8ad7, 2024-10-11)&quot;
        ///   sodipodi:docname=&quot;Component_Background.svg&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:xlink=&quot;http://www. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Component_Background {
            get {
                return ResourceManager.GetString("Component_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///
        ///&lt;svg
        ///   width=&quot;26.458334mm&quot;
        ///   height=&quot;26.458338mm&quot;
        ///   viewBox=&quot;0 0 26.458334 26.458338&quot;
        ///   version=&quot;1.1&quot;
        ///   id=&quot;svg1&quot;
        ///   xml:space=&quot;preserve&quot;
        ///   inkscape:version=&quot;1.4 (86a8ad7, 2024-10-11)&quot;
        ///   sodipodi:docname=&quot;Component_Background.svg&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:xlink=&quot;http://ww [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string E_Wire_Off {
            get {
                return ResourceManager.GetString("E_Wire_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///
        ///&lt;svg
        ///   width=&quot;26.458334mm&quot;
        ///   height=&quot;26.458336mm&quot;
        ///   viewBox=&quot;0 0 26.458334 26.458336&quot;
        ///   version=&quot;1.1&quot;
        ///   id=&quot;svg1&quot;
        ///   xml:space=&quot;preserve&quot;
        ///   inkscape:version=&quot;1.4 (86a8ad7, 2024-10-11)&quot;
        ///   sodipodi:docname=&quot;Component_Background.svg&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:xlink=&quot;http://ww [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string E_Wire_On {
            get {
                return ResourceManager.GetString("E_Wire_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///
        ///&lt;svg
        ///   width=&quot;26.458334mm&quot;
        ///   height=&quot;26.458336mm&quot;
        ///   viewBox=&quot;0 0 26.458334 26.458336&quot;
        ///   version=&quot;1.1&quot;
        ///   id=&quot;svg1&quot;
        ///   xml:space=&quot;preserve&quot;
        ///   inkscape:version=&quot;1.4 (86a8ad7, 2024-10-11)&quot;
        ///   sodipodi:docname=&quot;Component_Background.svg&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:xlink=&quot;http://ww [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Green_Led_On {
            get {
                return ResourceManager.GetString("Green_Led_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///
        ///&lt;svg
        ///   width=&quot;26.458342mm&quot;
        ///   height=&quot;26.45833mm&quot;
        ///   viewBox=&quot;0 0 26.458342 26.45833&quot;
        ///   version=&quot;1.1&quot;
        ///   id=&quot;svg1&quot;
        ///   xml:space=&quot;preserve&quot;
        ///   inkscape:version=&quot;1.4 (86a8ad7, 2024-10-11)&quot;
        ///   sodipodi:docname=&quot;Component_Background.svg&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:xlink=&quot;http://www. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Led_Off {
            get {
                return ResourceManager.GetString("Led_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///
        ///&lt;svg
        ///   width=&quot;26.458349mm&quot;
        ///   height=&quot;26.458334mm&quot;
        ///   viewBox=&quot;0 0 26.458349 26.458334&quot;
        ///   version=&quot;1.1&quot;
        ///   id=&quot;svg1&quot;
        ///   xml:space=&quot;preserve&quot;
        ///   inkscape:version=&quot;1.4 (86a8ad7, 2024-10-11)&quot;
        ///   sodipodi:docname=&quot;Component_Background.svg&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:xlink=&quot;http://ww [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string N_Wire_Off {
            get {
                return ResourceManager.GetString("N_Wire_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///
        ///&lt;svg
        ///   width=&quot;26.458334mm&quot;
        ///   height=&quot;26.458342mm&quot;
        ///   viewBox=&quot;0 0 26.458334 26.458341&quot;
        ///   version=&quot;1.1&quot;
        ///   id=&quot;svg1&quot;
        ///   xml:space=&quot;preserve&quot;
        ///   inkscape:version=&quot;1.4 (86a8ad7, 2024-10-11)&quot;
        ///   sodipodi:docname=&quot;Component_Background.svg&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:xlink=&quot;http://ww [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string N_Wire_On {
            get {
                return ResourceManager.GetString("N_Wire_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///
        ///&lt;svg
        ///   width=&quot;26.458328mm&quot;
        ///   height=&quot;26.458334mm&quot;
        ///   viewBox=&quot;0 0 26.458328 26.458334&quot;
        ///   version=&quot;1.1&quot;
        ///   id=&quot;svg1&quot;
        ///   xml:space=&quot;preserve&quot;
        ///   inkscape:version=&quot;1.4 (86a8ad7, 2024-10-11)&quot;
        ///   sodipodi:docname=&quot;Component_Background.svg&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:xlink=&quot;http://ww [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Red_Led_On {
            get {
                return ResourceManager.GetString("Red_Led_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///
        ///&lt;svg
        ///   width=&quot;26.458328mm&quot;
        ///   height=&quot;26.458334mm&quot;
        ///   viewBox=&quot;0 0 26.458328 26.458334&quot;
        ///   version=&quot;1.1&quot;
        ///   id=&quot;svg1&quot;
        ///   xml:space=&quot;preserve&quot;
        ///   inkscape:version=&quot;1.4 (86a8ad7, 2024-10-11)&quot;
        ///   sodipodi:docname=&quot;Component_Background.svg&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:xlink=&quot;http://ww [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S_Wire_Off {
            get {
                return ResourceManager.GetString("S_Wire_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///
        ///&lt;svg
        ///   width=&quot;26.458334mm&quot;
        ///   height=&quot;26.458338mm&quot;
        ///   viewBox=&quot;0 0 26.458334 26.458338&quot;
        ///   version=&quot;1.1&quot;
        ///   id=&quot;svg1&quot;
        ///   xml:space=&quot;preserve&quot;
        ///   inkscape:version=&quot;1.4 (86a8ad7, 2024-10-11)&quot;
        ///   sodipodi:docname=&quot;Component_Background.svg&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:xlink=&quot;http://ww [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S_Wire_On {
            get {
                return ResourceManager.GetString("S_Wire_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///
        ///&lt;svg
        ///   width=&quot;26.458328mm&quot;
        ///   height=&quot;26.458336mm&quot;
        ///   viewBox=&quot;0 0 26.458328 26.458336&quot;
        ///   version=&quot;1.1&quot;
        ///   id=&quot;svg1&quot;
        ///   xml:space=&quot;preserve&quot;
        ///   inkscape:version=&quot;1.4 (86a8ad7, 2024-10-11)&quot;
        ///   sodipodi:docname=&quot;Component_Background.svg&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:xlink=&quot;http://ww [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string W_Wire_Off {
            get {
                return ResourceManager.GetString("W_Wire_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///
        ///&lt;svg
        ///   width=&quot;26.458328mm&quot;
        ///   height=&quot;26.45833mm&quot;
        ///   viewBox=&quot;0 0 26.458328 26.45833&quot;
        ///   version=&quot;1.1&quot;
        ///   id=&quot;svg1&quot;
        ///   xml:space=&quot;preserve&quot;
        ///   inkscape:version=&quot;1.4 (86a8ad7, 2024-10-11)&quot;
        ///   sodipodi:docname=&quot;Component_Background.svg&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:xlink=&quot;http://www. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string W_Wire_On {
            get {
                return ResourceManager.GetString("W_Wire_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///
        ///&lt;svg
        ///   width=&quot;26.458349mm&quot;
        ///   height=&quot;26.45833mm&quot;
        ///   viewBox=&quot;0 0 26.458349 26.45833&quot;
        ///   version=&quot;1.1&quot;
        ///   id=&quot;svg1&quot;
        ///   xml:space=&quot;preserve&quot;
        ///   inkscape:version=&quot;1.4 (86a8ad7, 2024-10-11)&quot;
        ///   sodipodi:docname=&quot;Component_Background.svg&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:xlink=&quot;http://www. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string White_Led_On {
            get {
                return ResourceManager.GetString("White_Led_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///
        ///&lt;svg
        ///   width=&quot;26.458334mm&quot;
        ///   height=&quot;26.458342mm&quot;
        ///   viewBox=&quot;0 0 26.458334 26.458341&quot;
        ///   version=&quot;1.1&quot;
        ///   id=&quot;svg1&quot;
        ///   xml:space=&quot;preserve&quot;
        ///   inkscape:version=&quot;1.4 (86a8ad7, 2024-10-11)&quot;
        ///   sodipodi:docname=&quot;Component_Background.svg&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:xlink=&quot;http://ww [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Yellow_Led_On {
            get {
                return ResourceManager.GetString("Yellow_Led_On", resourceCulture);
            }
        }
    }
}
