name: Codacy Analysis CLI

on: 
   push:
      branches:
        - master
      paths-ignore:
        - .github/workflows/*
        - README.md
        - .gitignore
        - .devcontainer/*
   workflow_dispatch:

permissions:
  security-events: write
  actions: read
  contents: read
  
jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
          category: codacy
