name: codect_dockerize

on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/workflows/*
      - README.md
      - .gitignore
      - .devcontainer/*
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}
  DOTNET_VERSION: '8.0.x'
  SOLUTION_NAME: 'Codect'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Publish Application 🔨
        run: dotnet publish "${{ env.SOLUTION_NAME }}.API/${{ env.SOLUTION_NAME }}.API.csproj" -c Release -o ./publish /p:UseAppHost=false

      - name: Build Docker Image 🐳
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Log in to GitHub Container Registry 🔑
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image 🚢
        run: |
          docker tag ${{ env.IMAGE_NAME }}:latest ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
