name: codect_dockerize

on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/workflows/*
      - README.md
      - .gitignore
      - .devcontainer/*
  workflow_dispatch:

env:
  IMAGE_NAME: 'codect'
  DOTNET_VERSION: '8.0.x'
  SOLUTION_NAME: 'Codect'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Publish Application 🔨
        run: dotnet publish "${{ env.SOLUTION_NAME }}/${{ env.SOLUTION_NAME }}.csproj" -c Release -o ./publish /p:UseAppHost=false

      - name: Build and Push Docker Images with Compose 🐳
        run: |
  
          docker-compose -f docker-compose.yml build
          
          # Tag images
          docker tag codect_app:latest ghcr.io/${{ github.repository }}:app-latest
          docker tag codect_database_codect_container:latest ghcr.io/${{ github.repository }}:db-latest
          
          # Log in to GitHub Container Registry
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Push both images
          docker push ghcr.io/${{ github.repository }}:app-latest
          docker push ghcr.io/${{ github.repository }}:db-latest
